name: build-go-binary

on:
  release:
    types: [created] # Indicates that it is triggered when a new Release is created

jobs:
  build-go-binary:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        goos: [linux, windows, darwin]
        goarch: [amd64, arm64] # A packaged schema is required
    steps:
      - uses: actions/checkout@v3
      - uses: wangyoucao577/go-release-action@v1.51
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          goos: ${{ matrix.goos }}
          goarch: ${{ matrix.goarch }}
          goversion: 1.23
          binary_name: "mastodon-markdown-archive"
          extra_files: README.md

